![image.png](../img/Clase8_Ej1_fig1.png)

In [24]:
from control.matlab import *
from numpy.linalg import matrix_rank as rank
from numpy import zeros
from matplotlib import pyplot as plt

### Ejercicio parte a)
#### Carga del sistema

In [2]:
A = [[-1,-2,-2],[0,-1,1],[1,0,-1]]
B = [[2],[0],[1]]
C = [1,1,0]
D = 0
poles = [-1+2*1j, -1-2*1j, -6]

#### Verificación de controlabilidad

In [5]:
decision = '' if rank(ctrb(A,B)) == len(A) else "no "
print(f"{decision}es controlable")

es controlable


#### Hallar K a través de la función acker

In [7]:
K = acker(A,B,poles)
print(K)

[[ 3.4 12.4 -1.8]]


### Ejercicio parte b)
#### Carga del sistema

In [8]:
A = [[2,0,0],[0,2,0],[0,3,1]]
B = [[0,1],[1,0],[0,1]]
C = [[1,0,0],[0,1,0]]
D = 0

#### Se halla la K
El valor de la K puede variar porque pueden haber varios valores que cumplen con los requisitos para los polos deseados

In [22]:
print("Primer valor")
K1 = place(A,B,poles)
print(K1)
print("\nSegundo valor")
K2 = place_varga(A,B,poles)
print(K2)

Primer valor
[[-2.97329058  5.5330551   3.49073034]
 [ 4.56221081  1.70546321  2.90473409]]

Segundo valor
[[ 3.22744397  9.1353582   2.64916914]
 [ 5.21394975 -0.57827484 -1.34930795]]


Se tiene el sistema:  
$\dot{x}=A\cdot x+B\cdot u$

Pero sabemos que:  
$u = -K\cdot x$

Reemplazamos en la ecuación del sistema  
$\dot{x}=A\cdot x+B\cdot (-K\cdot x)$

Al final agrupamos de la siguiente forma:
$\dot{x}=(A-B\cdot K)\cdot x$

Ahora podemos decir que $A-B\cdot K$ es nuestra nueva $A'$ y suponemos una $B' = \begin{bmatrix} 0 & 0\\0 & 0\\0 & 0 \end{bmatrix}$

por lo que nuestro nuevo sistema quedará así:  
$\dot{x}=A'\cdot x+B'\cdot u = (A-B\cdot K)\cdot x + B'\cdot u$

Con dicho sistema se procede a la verificación:

In [26]:
A_prima1 = A-B*K1
B_prima1 = zeros((3,2))

A_prima2 = A-B*K2
B_prima2 = zeros((3,2))

sys1 = ss(A_prima1,B_prima1,C,D)
sys2 = ss(A_prima2,B_prima2,C,D)

print("Polos deseados")
print("\nPrimera opción:")
print(pole(sys1))
print("\nSegunda opción:")
print(pole(sys2))

Polos deseados

Primera opción:
[-6.+0.j -1.+2.j -1.-2.j]

Segunda opción:
[-1.+2.j -1.-2.j -6.+0.j]
